/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as SessionRoomRouteImport } from './routes/session/room'
import { Route as SessionCreateRouteImport } from './routes/session/create'
import { Route as QuizSummaryRouteImport } from './routes/quiz/summary'
import { Route as QuizStartScreenRouteImport } from './routes/quiz/start-screen'
import { Route as QuizQuestionsRouteImport } from './routes/quiz/questions'
import { Route as QuizExamRulesRouteImport } from './routes/quiz/exam-rules'
import { Route as QuizCreatorRouteImport } from './routes/quiz/creator'
import { Route as QuizQuestionListRouteImport } from './routes/quiz/question/list'
import { Route as QuizQuestionAddRouteImport } from './routes/quiz/question/add'
import { Route as QuizQuestionEditIdRouteImport } from './routes/quiz/question/edit.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoomRoute = SessionRoomRouteImport.update({
  id: '/session/room',
  path: '/session/room',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCreateRoute = SessionCreateRouteImport.update({
  id: '/session/create',
  path: '/session/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSummaryRoute = QuizSummaryRouteImport.update({
  id: '/quiz/summary',
  path: '/quiz/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizStartScreenRoute = QuizStartScreenRouteImport.update({
  id: '/quiz/start-screen',
  path: '/quiz/start-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionsRoute = QuizQuestionsRouteImport.update({
  id: '/quiz/questions',
  path: '/quiz/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizExamRulesRoute = QuizExamRulesRouteImport.update({
  id: '/quiz/exam-rules',
  path: '/quiz/exam-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCreatorRoute = QuizCreatorRouteImport.update({
  id: '/quiz/creator',
  path: '/quiz/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionListRoute = QuizQuestionListRouteImport.update({
  id: '/quiz/question/list',
  path: '/quiz/question/list',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionAddRoute = QuizQuestionAddRouteImport.update({
  id: '/quiz/question/add',
  path: '/quiz/question/add',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuestionEditIdRoute = QuizQuestionEditIdRouteImport.update({
  id: '/quiz/question/edit/$id',
  path: '/quiz/question/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/quiz/creator': typeof QuizCreatorRoute
  '/quiz/exam-rules': typeof QuizExamRulesRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/start-screen': typeof QuizStartScreenRoute
  '/quiz/summary': typeof QuizSummaryRoute
  '/session/create': typeof SessionCreateRoute
  '/session/room': typeof SessionRoomRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/quiz/question/add': typeof QuizQuestionAddRoute
  '/quiz/question/list': typeof QuizQuestionListRoute
  '/quiz/question/edit/$id': typeof QuizQuestionEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/quiz/creator': typeof QuizCreatorRoute
  '/quiz/exam-rules': typeof QuizExamRulesRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/start-screen': typeof QuizStartScreenRoute
  '/quiz/summary': typeof QuizSummaryRoute
  '/session/create': typeof SessionCreateRoute
  '/session/room': typeof SessionRoomRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/quiz/question/add': typeof QuizQuestionAddRoute
  '/quiz/question/list': typeof QuizQuestionListRoute
  '/quiz/question/edit/$id': typeof QuizQuestionEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/quiz/creator': typeof QuizCreatorRoute
  '/quiz/exam-rules': typeof QuizExamRulesRoute
  '/quiz/questions': typeof QuizQuestionsRoute
  '/quiz/start-screen': typeof QuizStartScreenRoute
  '/quiz/summary': typeof QuizSummaryRoute
  '/session/create': typeof SessionCreateRoute
  '/session/room': typeof SessionRoomRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/quiz/question/add': typeof QuizQuestionAddRoute
  '/quiz/question/list': typeof QuizQuestionListRoute
  '/quiz/question/edit/$id': typeof QuizQuestionEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/settings'
    | '/quiz/creator'
    | '/quiz/exam-rules'
    | '/quiz/questions'
    | '/quiz/start-screen'
    | '/quiz/summary'
    | '/session/create'
    | '/session/room'
    | '/users/$userId'
    | '/quiz/question/add'
    | '/quiz/question/list'
    | '/quiz/question/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/settings'
    | '/quiz/creator'
    | '/quiz/exam-rules'
    | '/quiz/questions'
    | '/quiz/start-screen'
    | '/quiz/summary'
    | '/session/create'
    | '/session/room'
    | '/users/$userId'
    | '/quiz/question/add'
    | '/quiz/question/list'
    | '/quiz/question/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/settings'
    | '/quiz/creator'
    | '/quiz/exam-rules'
    | '/quiz/questions'
    | '/quiz/start-screen'
    | '/quiz/summary'
    | '/session/create'
    | '/session/room'
    | '/users/$userId'
    | '/quiz/question/add'
    | '/quiz/question/list'
    | '/quiz/question/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  QuizCreatorRoute: typeof QuizCreatorRoute
  QuizExamRulesRoute: typeof QuizExamRulesRoute
  QuizQuestionsRoute: typeof QuizQuestionsRoute
  QuizStartScreenRoute: typeof QuizStartScreenRoute
  QuizSummaryRoute: typeof QuizSummaryRoute
  SessionCreateRoute: typeof SessionCreateRoute
  SessionRoomRoute: typeof SessionRoomRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  QuizQuestionAddRoute: typeof QuizQuestionAddRoute
  QuizQuestionListRoute: typeof QuizQuestionListRoute
  QuizQuestionEditIdRoute: typeof QuizQuestionEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/room': {
      id: '/session/room'
      path: '/session/room'
      fullPath: '/session/room'
      preLoaderRoute: typeof SessionRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/create': {
      id: '/session/create'
      path: '/session/create'
      fullPath: '/session/create'
      preLoaderRoute: typeof SessionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/summary': {
      id: '/quiz/summary'
      path: '/quiz/summary'
      fullPath: '/quiz/summary'
      preLoaderRoute: typeof QuizSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/start-screen': {
      id: '/quiz/start-screen'
      path: '/quiz/start-screen'
      fullPath: '/quiz/start-screen'
      preLoaderRoute: typeof QuizStartScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/questions': {
      id: '/quiz/questions'
      path: '/quiz/questions'
      fullPath: '/quiz/questions'
      preLoaderRoute: typeof QuizQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/exam-rules': {
      id: '/quiz/exam-rules'
      path: '/quiz/exam-rules'
      fullPath: '/quiz/exam-rules'
      preLoaderRoute: typeof QuizExamRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/creator': {
      id: '/quiz/creator'
      path: '/quiz/creator'
      fullPath: '/quiz/creator'
      preLoaderRoute: typeof QuizCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/question/list': {
      id: '/quiz/question/list'
      path: '/quiz/question/list'
      fullPath: '/quiz/question/list'
      preLoaderRoute: typeof QuizQuestionListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/question/add': {
      id: '/quiz/question/add'
      path: '/quiz/question/add'
      fullPath: '/quiz/question/add'
      preLoaderRoute: typeof QuizQuestionAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/question/edit/$id': {
      id: '/quiz/question/edit/$id'
      path: '/quiz/question/edit/$id'
      fullPath: '/quiz/question/edit/$id'
      preLoaderRoute: typeof QuizQuestionEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  QuizCreatorRoute: QuizCreatorRoute,
  QuizExamRulesRoute: QuizExamRulesRoute,
  QuizQuestionsRoute: QuizQuestionsRoute,
  QuizStartScreenRoute: QuizStartScreenRoute,
  QuizSummaryRoute: QuizSummaryRoute,
  SessionCreateRoute: SessionCreateRoute,
  SessionRoomRoute: SessionRoomRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  QuizQuestionAddRoute: QuizQuestionAddRoute,
  QuizQuestionListRoute: QuizQuestionListRoute,
  QuizQuestionEditIdRoute: QuizQuestionEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
